development:
   adapter: postgresql
   encoding: unicode
   database: techcamp_development
   pool: 5
   host: localhost
   port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: techcamp_test
  pool: 5